---
title: "plot_vernalis_salvage"
author: "Catarina Pien"
date: '2023-01-16'
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Plot Vernalis Flow with Delta Smelt Salvage

**Does Salvage occur when VNS > 8000 cfs?**
```{r, echo = FALSE}
library(tidyverse)
library(data.table) #rbindlist()
library(lubridate) #today()
library(readr)
library(here)
library(rvest)
library(flextable)
source("functions.R")
```

## Get Vernalis Flow

```{r, echo = FALSE}
start <- "2000-01-01"
end <- "2022-12-31"
#f_get_NWIS_flow(siteNumbers = 11303500) 
flow_Vernalis <- readRDS(here("data_raw/USGS_NWIS_11303500_flow.rds")) %>%
  rename(Datetime = date_time, 
         Flow = flow_inst)%>%
  mutate(Station = "VNS",
         Date = date(Datetime)) %>%
  select(Datetime, Date, Station, Flow) %>%
  pivot_longer(cols = Flow,
               names_to = "Parameter",
               values_to = "value") 

flow_vernalis_daily <- flow_Vernalis %>%
  rename(value_all = value) %>%
  group_by(Date, Station) %>%
  summarize(Flow = mean(value_all, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(Year = year(Date),
         Month = month(Date),
        WY = ifelse(Month>9, Year + 1, Year))
```

## Pull salvage from SacPAS
```{r, echo=FALSE}
# salvage_data<-pull_salvage() 
# saveRDS(salvage_data, "data_raw/smelt_salvage_data_raw.rds")

salvage_data <- readRDS("data_raw/smelt_salvage_data_raw.rds")
#str(salvage_data)
salvage_smelt <- salvage_data %>%
  filter(!is.na(Species)) %>%
  janitor::clean_names("upper_camel") %>%
  rename(Datetime = SampleTime) %>%
  mutate(Datetime=ymd_hms(Datetime),
         Date = date(Datetime)) %>%
  select(Datetime, Date, Facility, Species, CountDurationMinutes, PumpingDurationMinutes, StudyType, SampleFraction, Length, Nfish)

salvage_daily <- salvage_smelt %>%
  group_by(Date) %>%
  summarize(Salvage = sum(Nfish, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(Year = year(Date),
         Month = month(Date),
         WY = ifelse(Month>9, Year + 1, Year)) %>%
  filter(WY > 1999 & WY < 2023)
```

## Plot salvage with flows
```{r, echo = FALSE}
flow_salvage <- left_join(flow_vernalis_daily, salvage_daily) %>%
  mutate(Salvage = replace(Salvage, is.na(Salvage), 0),
         vns_flow = ifelse(Flow >= 8000, "VNS >= 8000", 
                                    "VNS < 8000"),
          threshold = ifelse(Salvage == 0, "No salvage", 
                             ifelse(Flow >= 8000, "VNS >= 8000", 
                                    "VNS < 8000")),
         salvageSc = Salvage * 100) %>%
  filter(WY < 2023)

# ggplot(flow_salvage) + 
#   geom_point(aes(Date, Flow), size = 0.8) +
#   geom_point(aes(Date, Salvage), color = "blue") + 
#   geom_hline(yintercept = 8000, color = "red") + 
#   scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
#   theme_bw()
```

```{r, echo = FALSE, fig.cap= "Vernalis Flow and Delta Smelt Salvage, WY 2000-2022. Black points are Flow, while colored points are Salvage multiplied by 100 (to better show up visually).", width = 8, height = 6}
ggplot(flow_salvage) + 
  geom_point(aes(Date, Flow), size = 0.8, color = "gray30") +
  geom_point(aes(Date, salvageSc, color = threshold), size = 1, shape = 24) + 
  geom_hline(yintercept = 8000, color = "red") + 
  scale_x_date(date_breaks = "1 year", date_labels = "%Y", expand = c(0,0)) + 
  scale_color_manual(values = c("gray", "slategray3", "goldenrod2"))+
  labs(y = "Vernalis Flow (cfs)", color = "Salvage") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90),
        axis.title.x = element_blank(),
        legend.position = "top")
```

```{r, echo = FALSE, fig.cap = "Incidents of Salvage when Vernalis Flow >= 8000 cfs"}
incidents <- flow_salvage %>%
  filter(vns_flow == "VNS >= 8000")

ggplot(incidents) + geom_col(aes(WY, Salvage)) + 
  scale_x_continuous(breaks = seq(2000,2022,1)) + 
  labs(y = "Salvage (Count)", x = "Water Year") +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90))
```

```{r, echo = FALSE}
tab <- incidents %>%
  select(WY, Salvage) %>%
  group_by(WY) %>%
  summarize(SumSalvage = sum(Salvage, na.rm = TRUE),
            DaysAboveFlowThreshold = n()) %>%
  ungroup() %>%
  mutate(WY = factor(WY)) 

flextable(tab) %>%
  set_caption("Summed Salvage During Periods Where VNS >= 8000 cfs") %>%
  width(width = c(0.5,1.5, 2))
```

