---
title: "spring_plot_flow"
author: "Catarina Pien"
date: '2023-03-01'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyr)
library(dataRetrieval)
library(here)
source("functions.R")
```

```{r}
wytype <- read.csv("data_raw/WYType.csv") %>%
  select(WY, Basin, Yr.type) %>%
  mutate(wy = as.numeric(WY)) %>%
  pivot_wider(names_from = "Basin", values_from = Yr.type, id_cols = "wy")
```

# Get flow data

WLK  = 11390500
```{r}
start = "1984-01-01"
end = "2023-01-01"
# f_get_NWIS_flow(siteNumbers = 11390500, startDate = start, endDate =end)

flow_WLK <- readRDS(here("data_raw", "USGS_NWIS_11390500_flow.rds")) %>%
  rename(Datetime = date_time, 
         flow = flow_inst)%>%
  mutate(station = "WLK",
         date = date(Datetime),
         datetime = Datetime) %>%
  select(datetime, date, station, flow) %>%
  pivot_longer(cols = flow,
               names_to = "parameter",
               values_to = "value") 

flow_WLK_daily <- flow_WLK %>%
  rename(value_all = value) %>%
  group_by(date, station) %>%
  summarize(value = mean(value_all, na.rm = TRUE)) %>%
  ungroup() %>%
  rename(flow = value)
```

```{r}
flow <- flow_WLK_daily %>%
  mutate(year = year(date),
         month = month(date),
         date2 = paste0(1980, "-", month, "-", day(date)),
         date2 = lubridate::ymd(date2),
         wy = ifelse(month>9, year+2, year)) %>%
  filter(!is.na(date)) %>%
  left_join(wytype) %>%
  mutate(fWY = factor(wy),
         index = 1:n()) %>%
  rename(wytype = SacramentoValley) %>%
  select(index, everything()) %>%
  select(-SanJoaquinValley) %>%
  filter(!is.na(wytype)) %>%
  mutate(wytype = factor(wytype, levels = c("W", "AN", "BN","D", "C"))) %>%
  mutate(TimePeriod= case_when(
    wy<2000 ~ "1970-1999",
    wy>=2000&wy<2011 ~ "2000-2010",
    wy>=2011 ~ "2011-2022"
)) %>%
  filter(month>2 & month<7)
```

```{r}
plot_flow <- ggplot2::ggplot(data=flow,aes(x=date2,y=flow,group=wy,color=wytype))+
  ggplot2::theme_bw()+
  ggplot2::geom_line(alpha=0.5)+
  facet_grid(TimePeriod~wytype)+
  geom_smooth(aes(group=wytype),se=F)+
  ggplot2::scale_colour_manual(values = c("#003E51","#007396","#C69214","#FF671F","#9A3324")) +
  ggplot2::scale_size_manual(values = c(0.5,0.5,0.5,0.5,0.5,1),name="",labels=c(2017:2022)) +
  ggplot2::theme(plot.title=element_text(size=9), 
                 axis.text.x=element_text(size=8, color="black",angle=90), 
                 axis.text.y = element_text(size=9, color="black"), 
                 axis.title.x = element_text(size = 10, angle = 00), 
                 axis.title.y = element_text(size = 10, angle = 90),
                 strip.text = element_text(size = 10),
                 legend.position = "none",
                 strip.background = element_rect(size=0.3)) + 
  ggplot2::ylab("Flow (cfs)")+
  ggplot2::xlab(NULL)+
  ggplot2::scale_x_date(date_labels = "%b",date_breaks  ="1 month")

plot_flow
```

# Save plot
```{r}
png(here("figures","flow_WLK_spring.tiff"),
     type="cairo",
     units="in", 
     width=8, #10*1, 
     height=5, #22*1, 
     pointsize=12, #12, 
     res=300)
print(plot_flow)
dev.off()
```

